[meta]
name        = "Discord Rivalry Ping"
author      = "FabianvZ, Lokulicious"
category    = "Utilities"
version     = "0.2"
blocks      = ["GrindingStats"]

[script]
dependencies = [ "NadeoServices"]
optional_dependencies = [ "ChampionMedals", "Discord" ]
