[meta]
name        = "DiscordClubHook"
author      = "FabianvZ"
category    = "Utilities"
version     = "0.1"
blocks      = ["GrindingStats"]

[script]
dependencies = [ "NadeoServices"]
optional_dependencies = [ "ChampionMedals", "Discord" ]
