[meta]
name        = "Discord Rivalry Ping"
author      = "FabianvZ, Lokulicious"
category    = "Utilities"
version     = "0.1"

[script]
dependencies = [ "NadeoServices" ]
optional_dependencies = [ "ChampionMedals", "Discord" ]
